export interface ExportOptions {
  reportName: string;
  generatedBy?: string;
  filters?: Record<string, any>;
  headers: string[];
  data: Record<string, any>[];
}

export function generateCSV(options: ExportOptions): string {
  const companyHeader = `# POOJA TRAVELS & CARGO - SHIPKART ENTERPRISE BI REPORT`;
  const reportHeader = `# Report Name: ${options.reportName}`;
  const generatedHeader = `# Generated By: ${options.generatedBy || 'System Admin'} on ${new Date().toLocaleString('en-IN')}`;
  const filterHeader = `# Applied Filters: ${JSON.stringify(options.filters || {})}`;
  const recordHeader = `# Total Records: ${options.data.length}\n`;

  const csvRows: string[] = [companyHeader, reportHeader, generatedHeader, filterHeader, recordHeader];

  // Table Column Headers
  csvRows.push(options.headers.map((h) => `"${h.replace(/"/g, '""')}"`).join(','));

  // Data Rows
  options.data.forEach((row) => {
    const values = options.headers.map((headerKey) => {
      const val = row[headerKey] !== undefined && row[headerKey] !== null ? String(row[headerKey]) : '';
      return `"${val.replace(/"/g, '""')}"`;
    });
    csvRows.push(values.join(','));
  });

  return csvRows.join('\n');
}

export function formatExportFilename(reportType: string, extension: 'csv' | 'xlsx' = 'csv'): string {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');

  const cleanType = reportType.toUpperCase().replace(/[^A-Z0-9]/g, '_');
  return `${cleanType}_${yyyy}_${mm}_${dd}_${hh}${min}.${extension}`;
}
